#   AUTO-MAS: A Multi-Script, Multi-Config Management and Automation Software
#   Copyright © 2025-2026 AUTO-MAS Team

#   This file incorporates work covered by the following copyright and
#   permission notice:
#
#       better-genshin-impact Copyright © 2023-2026 babalae
#       https://github.com/babalae/better-genshin-impact

#   This file is part of AUTO-MAS.

#   AUTO-MAS is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as
#   published by the Free Software Foundation, either version 3 of
#   the License, or (at your option) any later version.

#   AUTO-MAS is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty
#   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
#   the GNU Affero General Public License for more details.

#   You should have received a copy of the GNU Affero General Public License
#   along with AUTO-MAS. If not, see <https://www.gnu.org/licenses/>.

#   Contact: DLmaster_361@163.com

main:
  # 自定义按钮可触发的事件
  web_trigger_one:
    - runner:
        cpus: 1
      docker:
        image: python:3.11@sha256:70e8e937c1da72df1688e883a2108b0feff03381187fa78eca6d9b10df411320 # 3.11.16-trixie
      imports:
        - https://cnb.cool/AUTO-MAS-Project/secret/-/blob/main/env.yml
      stages:
        - name: 下载构建物并上传
          script: |
              cd .github/workflows
              pip install -r requirements.txt
              python github_download_and_cnb_upload.py --cnb-token $CNB_TOKEN --github-token $GITHUB_TOKEN --version-tag "$VERSION_TAG" --is-prerelease "$IS_PRERELEASE" --target-commitish main --release-body "$RELEASE_BODY"
              echo done!
  api_trigger_one:
    - runner:
        cpus: 1
      docker:
        image: python:3.11@sha256:70e8e937c1da72df1688e883a2108b0feff03381187fa78eca6d9b10df411320 # 3.11.16-trixie
      imports:
        - https://cnb.cool/AUTO-MAS-Project/secret/-/blob/main/env.yml
      stages:
        - name: API触发上传
          script: |
              echo run id: $RUN_ID
              cd .github/workflows
              pip install -r requirements.txt
              python github_download_and_cnb_upload.py --cnb-token $CNB_TOKEN --github-token $GITHUB_TOKEN --run-id $RUN_ID --version-tag "$VERSION_TAG" --is-prerelease "$IS_PRERELEASE" --target-commitish main --release-body "$RELEASE_BODY"
              echo api done!

dev:
  # 自定义按钮可触发的事件
  web_trigger_one:
    - runner:
        cpus: 1
      docker:
        image: python:3.11@sha256:70e8e937c1da72df1688e883a2108b0feff03381187fa78eca6d9b10df411320 # 3.11.16-trixie
      imports:
        - https://cnb.cool/AUTO-MAS-Project/secret/-/blob/main/env.yml
      stages:
        - name: 下载构建物并上传
          script: |
              cd .github/workflows
              pip install -r requirements.txt
              python github_download_and_cnb_upload.py --cnb-token $CNB_TOKEN --github-token $GITHUB_TOKEN --version-tag "$VERSION_TAG" --is-prerelease "$IS_PRERELEASE" --target-commitish dev --release-body "$RELEASE_BODY"
              echo done!
  api_trigger_one:
    - runner:
        cpus: 1
      docker:
        image: python:3.11@sha256:70e8e937c1da72df1688e883a2108b0feff03381187fa78eca6d9b10df411320 # 3.11.16-trixie
      imports:
        - https://cnb.cool/AUTO-MAS-Project/secret/-/blob/main/env.yml
      stages:
        - name: API触发上传
          script: |
              echo run id: $RUN_ID
              cd .github/workflows
              pip install -r requirements.txt
              python github_download_and_cnb_upload.py --cnb-token $CNB_TOKEN --github-token $GITHUB_TOKEN --run-id $RUN_ID --version-tag "$VERSION_TAG" --is-prerelease "$IS_PRERELEASE" --target-commitish dev --release-body "$RELEASE_BODY"
              echo api done!
