[project]
name = "auto-mas"
version = "5.2.0"
description = "A Multi-Script, Multi-Config Management and Automation Software"
requires-python = "~=3.12.0"
license = "AGPL-3.0-or-later"
dependencies = [
    "loguru==0.7.3",
    "fastapi==0.116.1",
    "pydantic==2.11.7",
    "uvicorn==0.35.0",
    "websockets==15.0.1",
    "aiofiles==24.1.0",
    "aiohttp==3.13.3",
    "httpx[socks]==0.28.1",
    "gitpython==3.1.45",
    "plyer==2.1.0",
    "psutil==7.0.0",
    "jinja2==3.1.6",
    "pywin32==310",
    "keyboard==0.13.5",
    "pycryptodome==3.23.0",
    "truststore==0.10.1",
    "pillow==12.1.1",
    "packaging==25.0",
    "rapidocr_onnxruntime==1.2.3",
    "pygetwindow==0.0.9",
    "pyautogui==0.9.54",
    "pynput==1.8.1",
    "numpy==2.3.4",
    "opencv-python==4.10.0.84",
    "maafw==5.8.1",
    "mss==9.0.2",
    "fastapi-mcp==0.4.0",
    "json5==0.14.0",
    "watchdog==6.0.0",
]

[dependency-groups]
dev = [
    "auto-mas-core",
]
plugins = [
    "auto-mas-core",
    "automas-m9a",
    "automas-maafw-agent-env",
    "automas-maafw-controller-adb",
    "automas-maafw-controller-win32",
    "automas-maafw-interface",
    "automas-maafw-project-update",
    "automas-maafw-runner",
    "automas-script-maafw",
    "automas-script-maafw-pack-m9a",
    "automas_plugin_okww_adapter",
]

[tool.auto-mas.plugin-bootstrap]
# 支持两种写法：
# 1) 仅声明包名： "automas_script_maa"
# 2) 声明固定版本： { name = "automas_script_maa", version = "0.0.5-alpha" }
# 3) 声明任意版本约束： { name = "automas_script_maa", specifier = ">=0.0.5-alpha,<0.1.0" }
packages = []

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "plugins/auto_mas_core",
    "plugins/automas_m9a",
    "plugins/automas_maafw_agent_env",
    "plugins/automas_maafw_controller_adb",
    "plugins/automas_maafw_controller_win32",
    "plugins/automas_maafw_interface",
    "plugins/automas_maafw_project_update",
    "plugins/automas_maafw_runner",
    "plugins/automas_script_maafw",
    "plugins/automas_script_maafw_pack_m9a",
    "plugins/okww_adapter",
]
exclude = [
    "plugins/pypi",
    "plugins/_generated",
]

[tool.uv.sources]
"auto-mas-core" = { workspace = true }
"automas-m9a" = { workspace = true }
"automas-maafw-agent-env" = { workspace = true }
"automas-maafw-controller-adb" = { workspace = true }
"automas-maafw-controller-win32" = { workspace = true }
"automas-maafw-interface" = { workspace = true }
"automas-maafw-project-update" = { workspace = true }
"automas-maafw-runner" = { workspace = true }
"automas-script-maafw" = { workspace = true }
"automas-script-maafw-pack-m9a" = { workspace = true }
"automas_plugin_okww_adapter" = { workspace = true }
